[server]
#host = "192.168.70.174:38080"
host = "127.0.0.1:38080"

[client]
name = "ubuntu223"            # 全局唯一的客户端名称

[[map]]
local-port = 9090
server-port = 9091

[[map]]
local-port = 22
server-port = 30022

